project:
  type: website
  output-dir: docs

website:
  title: "SRV-workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Lectures"
        contents:
          - lecture-01-intro-km-rmst.qmd
       
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show R code"
    code-tools: true
    number-sections: true

